SYSTEM:
  seed: 2007066439
  device: gpu
  num_devices: 1

rules: class,ooe,affordance,utility

DATA:
  train_tensors_path: files/data/tensors/consor_2023_08_19_15_52_19_seen_objects_train.pt
  val_tensors_path: files/data/tensors/consor_2023_08_19_15_52_19_seen_objects_val.pt
  seen_test_tensors_path: files/data/tensors/consor_2023_08_19_15_52_19_seen_objects_test.pt
  unseen_test_tensors_path: files/data/tensors/consor_2023_08_19_15_52_19_unseen_objects_test.pt
  seen_test_json_path: files/data/json/consor_2023_08_19_15_52_19_seen_objects_test.json
  unseen_test_json_path: files/data/json/consor_2023_08_19_15_52_19_unseen_objects_test.json

TRAIN:
  num_epochs: 30
  batch_size: 64
  lrate: 1e-3
  wt_decay: 1e-20
  log_folder: ./logs

MODEL:
  edge_feature_len: 1
  num_heads: 2
  num_layers: 3
  hidden_layer_size: 256 
  output_dimension: 64
  dropout: 0.5

LOSS:
  loss_fn: triplet_margin
  triplet_margin: 0.75 # 0.75

TEST:
  ckpt: files/consor_checkpoint/consor_2023_08_21_16_56_24-epoch=19-step=37240-success_rate=1.00.pth.ckpt
  results_folder: ./logs